name: Gradle Test

on:
  pull_request:
    branches:
        - 'main'
    types: [opened, reopened]

jobs:
  build:
    name: Run Gradle Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: "adopt"
          
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          distribution: "adopt"
          
#       - name: Update Gradle
#         run: ./gradlew wrapper --gradle-version 7.2

      - name: Build with Gradle
        run: ./gradlew clean test
        
      - name: Merge PR on success
        if: ${{ success() }}
        uses: pascalgn/automerge-action@v0.11.0
        with:
          github_token: ${{ secrets.AUTO_MERGE_TOKEN }}
          source_repo: ${{ github.repository }}
          source_branch: ${{ github.head_ref }}
          destination_branch: ${{ github.base_ref }}
        

